name: Run API Tests

on:
  push:
    branches:
      - main
      - master
    branches-ignore:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run API tests
      run: |
        pytest tests/ -v --alluredir=./allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y allure

    - name: Load test report history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-history

    - name: Prepare Allure history
      if: always()
      run: |
        mkdir -p allure-results/history
        if [ -d "gh-pages-history/history" ]; then
          cp -r gh-pages-history/history allure-results/history/
        fi

    - name: Generate Allure report
      if: always()
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report